//@version=4

//This indicator was made to allow three moving averages to be displayed without needing to use up 3 charting indicators individually

strategy(title="3MA Strategy", default_qty_value = 50, overlay = true, initial_capital=50000, default_qty_type = strategy.cash, commission_type =  strategy.commission.percent, commission_value = 0.05, calc_on_every_tick=true)

//Time window for strategy

// === INPUT BACKTEST RANGE ===
fromDay   = input(defval = 1,    title = "From Day",        type = input.integer, minval = 1, maxval = 31)
fromMonth = input(defval = 3,    title = "From Month",      type = input.integer, minval = 1, maxval = 12)
fromYear  = input(defval = 2020, title = "From Year",       type = input.integer, minval = 1970)
thruDay   = input(defval = 15,    title = "Thru Day",        type = input.integer, minval = 1, maxval = 31)
thruMonth = input(defval = 9,    title = "Thru Month",      type = input.integer, minval = 1, maxval = 12)
thruYear  = input(defval = 2020, title = "Thru Year",       type = input.integer, minval = 1970)

// === FUNCTION EXAMPLE ===
start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)        // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)        // backtest finish window
window()  => time >= start and time <= finish ? true : false       // create function "within window of time"

// Checkbox's for the other 2 MA's
showSecondMA = input(true, title="Enable 2nd MA")
ShowThirdMA = input(true, title="Enable 3rd MA")

len = input(5, minval=1, title="Length")
len2 = input(8, minval=1, title="Length2")
len3 = input(13, minval=1, title="Length3")

// len = input(9, minval=1, title="Length")
// len2 = input(21, minval=1, title="Length2")
// len3 = input(50, minval=1, title="Length3")

src = input(close, title="Source")
src2 = input(close, title="Source2")
src3 = input(close, title="Source3")

short = ema(src, len)
long = ema(src2, len2)
longest = ema(src3, len3)

plot(short, title="short EMA", color=color.red)
plot(showSecondMA and long ? long: na, title="long EMA", color=color.green)
plot(ShowThirdMA and longest ? longest: na, title="longest EMA", color=color.blue)

// MA cross alert
BuyMAcrossing = crossover(short, long)
SellMAcrossing = crossover(long, short)
BuylongestMAcrossing = crossover(long, longest)
SelllongestMAcrossing = crossover(longest, long)
// plot(BuyMAcrossing, style = plot.style_cross, linewidth = 4,color=color.black)

TrendingUp() => short > long
TrendingDown() => short < long
LongestAbove() => longest > long
LongestBelow() => longest < long

Uptrend() => TrendingUp() and BuyMAcrossing 
Downtrend() => TrendingDown() and SellMAcrossing

stongBuy() => (Uptrend() and LongestBelow()) or (BuylongestMAcrossing)
stongSell() => (Downtrend() and LongestAbove()) or (SelllongestMAcrossing)
plotshape(stongBuy(), color=color.black, style=shape.arrowup, text="Buy", location=location.bottom)
plotshape(stongSell(), color=color.black, style=shape.arrowdown, text="Sell", location=location.top)
bgcolor(stongBuy() ? color.green : stongSell() ? color.red : na,transp=50)

quanitity = input(50, "Quanitity input")

strategy.entry("long",   true, quanitity, when = stongBuy() and window())
strategy.entry("short", false, quanitity, when = stongSell() and window())

strategy.close("long", when = TrendingDown())
strategy.close("short", when = TrendingUp())