//@version=4
strategy(title="ATR + EMA + SMA Strategy", default_qty_value = 50, overlay = true, initial_capital=50000, default_qty_type = strategy.cash, commission_type =  strategy.commission.percent, commission_value = 0.05, calc_on_every_tick=true)


//Time window for strategy

// === INPUT BACKTEST RANGE ===
fromDay   = input(defval = 1,    title = "From Day",        type = input.integer, minval = 1, maxval = 31)
fromMonth = input(defval = 1,    title = "From Month",      type = input.integer, minval = 1, maxval = 12)
fromYear  = input(defval = 2020, title = "From Year",       type = input.integer, minval = 1970)
thruDay   = input(defval = 30,    title = "Thru Day",        type = input.integer, minval = 1, maxval = 31)
thruMonth = input(defval = 9,    title = "Thru Month",      type = input.integer, minval = 1, maxval = 12)
thruYear  = input(defval = 2020, title = "Thru Year",       type = input.integer, minval = 1970)

// === FUNCTION EXAMPLE ===
start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)        // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)        // backtest finish window
window()  => time >= start and time <= finish ? true : false       // create function "within window of time"

//Exit at the end of day everyday

intraday_sess = "0915-1500"
t = time(timeframe.period, intraday_sess)
sess_over = not na(t[1]) and na(t)
strategy.close_all(when = sess_over)

Source = input(title="Source", type=input.source, defval=close)
priceList = security(syminfo.tickerid, timeframe.period, Source)
smaLength = input(title="sma Length", type=input.integer, defval=13, minval=2)
TriggerPrice = input(title="Trigger Price", type=input.source, defval=close)

//ATR trendline

Atr=input(defval=5,title="Atr Period",minval=1,maxval=500)
Hhv=input(defval=10,title="HHV Period",minval=1,maxval=500)
Mult=input(defval=2.5,title="Multiplier",minval=0.1)
Barcolor=input(true,title="Barcolor")

TS=highest(high-Mult*atr(Atr),Hhv),barssince(close>highest(high-Mult*atr(Atr),Hhv) and close>close)
Color=iff(close>TS,color.green,iff(close<TS,color.red,color.black))
barcolor(Barcolor? Color:na)
plot(TS,color=Color,linewidth=3,title="ATR Trailing Stoploss")

atrTrendLineBuy=crossover(close,TS)
atrTrendLineSell=crossunder(close,TS)

// plotshape(atrTrendLineBuy,color=color.green,text="Buy",location=location.belowbar,style=shape.labelup,textcolor=color.white,transp=10)
// plotshape(atrTrendLineSell,color=color.red,text="Sell",style=shape.labeldown,textcolor=color.white,transp=10)

// alertcondition(atrTrendLineBuy, "Buy Signal", "Buy ATR Trailing Stoploss")
// alertcondition(atrTrendLineSell, "Sell Signal", "Sell ATR Trailing Stoploss")

//ATR trailing stop loss
atrSensitivity = input(7, title = "Key Vaule. 'This changes the sensitivity'")
atrPeriod = input(14, title = "ATR Period")

xATR  = atr(atrPeriod)
nLoss = atrSensitivity * xATR
xATRTrailingStop = 0.0

// isLastTwoPricesGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0)
// isLastTwoPricesSmallerThanStop() => priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0)
// isPriceGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0)

xATRTrailingStop := iff(priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), priceList - nLoss),
   iff(priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), priceList + nLoss), 
   iff(priceList > nz(xATRTrailingStop[1], 0), priceList - nLoss, priceList + nLoss)))
   
pos = 0
xEMA = ema(priceList, smaLength)
above = crossover(xEMA, xATRTrailingStop)
below = crossover(xATRTrailingStop, xEMA)

pos := iff(TriggerPrice > xEMA, 1,
         iff(TriggerPrice < xEMA, -1, nz(pos[1], 0)))
possig =iff(pos[1] != pos, pos, 0)

quanitity = input(50, "Quanitity input")

buy() => (((possig == 1)  or (priceList > xATRTrailingStop and above)) and atrTrendLineBuy)
buyExit() => (possig == -1) or (priceList < xATRTrailingStop and below)

sell() => (((possig == -1) or (priceList < xATRTrailingStop and below)) and atrTrendLineSell)
sellExit() => (possig == 1)  or (priceList > xATRTrailingStop and above)

if (buy() and window())
    strategy.entry("Long", strategy.long, quanitity)
if (sell() and window())
    strategy.entry("Short", strategy.short, quanitity)

strategy.close("Long", when = buyExit(), comment = "Exit long")
strategy.close("Short", when = sellExit(),  comment = "Exit Short")


plot(xEMA, title='EMA', color=#00ffaa, linewidth=2, style=plot.style_line)
