//@version=4
study(title="ATR + EMA + SMA Study", overlay = true)

Source = input(title="Source", type=input.source, defval=close)
priceList = security(syminfo.tickerid, timeframe.period, Source)
smaLength = input(title="sma Length", type=input.integer, defval=13, minval=2)
TriggerPrice = input(title="Trigger Price", type=input.source, defval=close)
PlaySafe = input(title="Play safe", type=input.bool, defval=false)

atrSensitivity = input(7,     title = "Key Vaule. 'This changes the sensitivity'")
atrPeriod = input(14,    title = "ATR Period")

xATR  = atr(atrPeriod)

nLoss = atrSensitivity * xATR

xATRTrailingStop = 0.0

// isLastTwoPricesGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0)
// isLastTwoPricesSmallerThanStop() => priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0)
// isPriceGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0)

xATRTrailingStop := iff(priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), priceList - nLoss),
   iff(priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), priceList + nLoss), 
   iff(priceList > nz(xATRTrailingStop[1], 0), priceList - nLoss, priceList + nLoss)))
   
pos = 0
xEMA = ema(priceList, smaLength)

above = crossover(xEMA, xATRTrailingStop)
below = crossover(xATRTrailingStop, xEMA)

pos := iff(TriggerPrice > xEMA, 1,
         iff(TriggerPrice < xEMA, -1, nz(pos[1], 0)))
possig =iff(pos[1] != pos, pos, 0)

buy() => PlaySafe ? possig == 1  and priceList > xATRTrailingStop and above : (possig == 1)  or (priceList > xATRTrailingStop and above)

sell() =>  PlaySafe ? possig == -1 and priceList < xATRTrailingStop and below : (possig == -1) or (priceList < xATRTrailingStop and below)

diff = TriggerPrice - xEMA

actionThreshold = input(15, title = "Action Threshold")

timeForAction() => (diff < actionThreshold) and (diff > actionThreshold-actionThreshold*2)? 1 : 0

bgcolor(buy() ? color.green : sell() ? color.red : na,transp=50)
plotshape(buy(), color=color.black, style=shape.arrowup, text="Buy", location=location.bottom)
plotshape(sell(), color=color.black, style=shape.arrowdown, text="Sell", location=location.top)
// plotchar(timeForAction(), "action")
alertcondition(buy() or sell(), title='Alert from ATR EMA study', message='Alert')

plot(xEMA, title='EMA', color=#00ffaa, linewidth=2, style=plot.style_line)