//@version=4
study(title="ATR + EMA + SMA Study", overlay = true)

Source = input(title="Source", type=input.source, defval=close)
priceList = security(syminfo.tickerid, timeframe.period, Source)
smaLength = input(title="sma Length", type=input.integer, defval=13, minval=2)
TriggerPrice = input(title="Trigger Price", type=input.source, defval=close)
PlaySafe = input(title="Play safe", type=input.bool, defval=false)

atrSensitivity = input(7,     title = "Key Vaule. 'This changes the sensitivity'")
atrPeriod = input(14,    title = "ATR Period")

xATR  = atr(atrPeriod)

nLoss = atrSensitivity * xATR

xATRTrailingStop = 0.0

// isLastTwoPricesGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0)
// isLastTwoPricesSmallerThanStop() => priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0)
// isPriceGreaterThanStop() => priceList > nz(xATRTrailingStop[1], 0)

xATRTrailingStop := iff(priceList > nz(xATRTrailingStop[1], 0) and priceList[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), priceList - nLoss),
   iff(priceList < nz(xATRTrailingStop[1], 0) and priceList[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), priceList + nLoss), 
   iff(priceList > nz(xATRTrailingStop[1], 0), priceList - nLoss, priceList + nLoss)))
   
pos = 0
xEMA = ema(priceList, smaLength)

above = crossover(xEMA, xATRTrailingStop)
below = crossover(xATRTrailingStop, xEMA)

pos := iff(TriggerPrice > xEMA, 1,
         iff(TriggerPrice < xEMA, -1, nz(pos[1], 0)))
possig =iff(pos[1] != pos, pos, 0)

buy() => PlaySafe ? possig == 1  and priceList > xATRTrailingStop and above : (possig == 1)  or (priceList > xATRTrailingStop and above)
sell() =>  PlaySafe ? possig == -1 and priceList < xATRTrailingStop and below : (possig == -1) or (priceList < xATRTrailingStop and below)

//Doji Candle check
C_Len = 14 // ema depth for bodyAvg
C_ShadowPercent = 5.0 // size of shadows
C_ShadowEqualsPercent = 100.0
C_DojiBodyPercent = 5.0
C_Factor = 2.0 // shows the number of times the shadow dominates the candlestick body

C_BodyHi = max(close, open)
C_BodyLo = min(close, open)
C_Body = C_BodyHi - C_BodyLo
C_BodyAvg = ema(C_Body, C_Len)
C_SmallBody = C_Body < C_BodyAvg
C_LongBody = C_Body > C_BodyAvg
C_UpShadow = high - C_BodyHi
C_DnShadow = C_BodyLo - low
C_HasUpShadow = C_UpShadow > C_ShadowPercent / 100 * C_Body
C_HasDnShadow = C_DnShadow > C_ShadowPercent / 100 * C_Body
C_WhiteBody = open < close
C_BlackBody = open > close
C_Range = high-low
C_IsInsideBar = C_BodyHi[1] > C_BodyHi and C_BodyLo[1] < C_BodyLo
C_BodyMiddle = C_Body / 2 + C_BodyLo
C_ShadowEquals = C_UpShadow == C_DnShadow or (abs(C_UpShadow - C_DnShadow) / C_DnShadow * 100) < C_ShadowEqualsPercent and (abs(C_DnShadow - C_UpShadow) / C_UpShadow * 100) < C_ShadowEqualsPercent
C_IsDojiBody = C_Range > 0 and C_Body <= C_Range * C_DojiBodyPercent / 100
C_Doji = C_IsDojiBody and C_ShadowEquals

patternLabelPosLow = low - (atr(30) * 0.6)
patternLabelPosHigh = high + (atr(30) * 0.6)

C_DojiNumberOfCandles = 1
C_DragonflyDoji = C_IsDojiBody and C_UpShadow <= C_Body
C_GravestoneDojiOne = C_IsDojiBody and C_DnShadow <= C_Body
alertcondition(C_Doji and not C_DragonflyDoji and not C_GravestoneDojiOne, title = "Doji", message = "New Doji pattern detected.")
if C_Doji and not C_DragonflyDoji and not C_GravestoneDojiOne
    var ttDoji = "Doji\nWhen the open and close of a security are essentially equal to each other, a doji candle forms. The length of both upper and lower shadows may vary, causing the candlestick you are left with to either resemble a cross, an inverted cross, or a plus sign. Doji candles show the playout of buyer-seller indecision in a tug-of-war of sorts. As price moves either above or below the opening level during the session, the close is either at or near the opening level."
    label.new(bar_index, patternLabelPosLow, text="D", style=label.style_label_up, color = color.gray, textcolor=color.white, tooltip = ttDoji)

isDoji() => highest(C_Doji?1:0, C_DojiNumberOfCandles)!=0
isNotDoji() => isDoji() == 0

bgcolor(isDoji()? color.gray : na, offset=-(C_DojiNumberOfCandles-1))

bgcolor(buy() ? color.green : sell() ? color.red : na,transp=50)
plotshape(buy(), color=color.black, style=shape.arrowup, text="Buy", location=location.bottom)
plotshape(sell(), color=color.black, style=shape.arrowdown, text="Sell", location=location.top)
// plotchar(timeForAction(), "action")
alertcondition(buy() or sell(), title='Alert from ATR EMA study', message='Alert')

plot(xEMA, title='EMA', color=#00ffaa, linewidth=2, style=plot.style_line)