// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © parabveer01
//@version=4


// high, low band
lower = low
upper = high
l = plot(lower, color=color.silver)
u = plot(upper, color=color.silver)
fill(u, l, color=color.silver)

// pivot
pivot = (high + low + close ) / 3.0

// bar color
TrendingUp() => close > close[1] and hl2 > hl2[1] and close > pivot
TrendingDown() => close < close[1] and hl2 < hl2[1] and close < pivot
barcolor(TrendingUp() ? color.green : TrendingDown() ? color.red : color.blue)

// background color
bgcolor(TrendingUp() and TrendingDown()[1] ? color.green : TrendingDown() and TrendingUp()[1] ? color.red : na)

// buy, sell signals
bearish = cross(close,pivot) == 1 and close[1] > close
bullish = cross(close,pivot) == 1 and close[1] < close
plotshape(bearish, color=color.maroon, style=shape.arrowdown, text="Sell", location=location.abovebar)
plotshape(bullish, color=color.olive, style=shape.arrowup, text="Buy", location=location.belowbar)

// strong buy, strong sell signals
verybearish = cross(close,pivot) == 1 and close[1] > close and TrendingDown()
verybullish = cross(close,pivot) == 1 and close[1] < close and TrendingUp()
plotshape(verybearish, color=color.fuchsia, style=shape.arrowdown, text="Sell", location=location.abovebar)
plotshape(verybullish, color=color.lime, style=shape.arrowup, text="Buy", location=location.belowbar)